### ISSUE TITLE
Implementación de test 

### ISSUE THREAD

**Issue by Jaim8RR** [Jaim8RR/GestorPalabras#2]
Los metodos de la clase GestorPalabras no tienen implementados ningún test en la clase GestorPalabrasTest
![clasevacia](https://github.com/Jaim8RR/GestorPalabras/assets/153544634/822332c0-fb2a-4e02-933b-1846a48ca4e4)

**Comment by Jaim8RR** [comment]
@gonzaga24 ha añadido un test pero se necesitan más empecemos por poner los más simples

**Comment by gonzaga24** [comment]
Ya estan todos los metodos introducidos
