### ISSUE TITLE
Los test de palindromo no pasan 

### ISSUE THREAD

**Issue by Jaim8RR** [Jaim8RR/GestorPalabras#3]
Hay que modificar el metodo de la clase gestor palabras parece que el error va relacionado con las tildes. Las cuales entiendo que no deberian impedir que sean o no palindromos.
![imagen](https://github.com/Jaim8RR/GestorPalabras/assets/153544634/1af40c4b-03c3-46e3-8552-01cf6943dd84)
![imagen](https://github.com/Jaim8RR/GestorPalabras/assets/153544634/6b22b6a9-379e-49e9-b8b5-7630f4bb5c52)

**Comment by gonzaga24** [comment]
Ha sido arreglado
