### ISSUE TITLE
Los Tests de invertir palabra no pasan

### ISSUE THREAD

**Issue by danielantmann** [Jaim8RR/GestorPalabras#4]
Ejecute esto:

    @Test
    public void testInvertirPalabraPalabrasSimples() {
        assertEquals("aloh", gestor.invertirPalabra("hola"));
        assertEquals("asem", gestor.invertirPalabra("mesa"));
        assertEquals("asac", gestor.invertirPalabra("casa"));
    }

    @Test
    public void testInvertirPalabra_Mayusculas() {
        assertEquals("ALOH", gestor.invertirPalabra("HOLA"));
        assertEquals("AMESA", gestor.invertirPalabra("MESA"));
        assertEquals("ASAC", gestor.invertirPalabra("CASA"));
    }

    @Test
    public void testInvertirPalabraNúmeros() {
        assertEquals("54321", gestor.contarVocales("12345"));
        assertEquals("1234567890", gestor.contarVocales("9876543210"));
    }

y los resultados no son los esperados.

**Comment by gonzaga24** [comment]
Se han arreglado
