### ISSUE TITLE
Los test de ContarVocales no pasan

### ISSUE THREAD

**Issue by gonzaga24** [Jaim8RR/GestorPalabras#5]
![image](https://github.com/Jaim8RR/GestorPalabras/assets/153544688/f72806bf-b439-4632-953b-b37979da8b8d)

Al introducir estos tests no dan el resultado deseado:
    
    @Test
    public void testContarVocalesPalabrasSimples() {
        assertEquals(3, gestor.contarVocales("hablame"));
        assertEquals(4, gestor.contarVocales("olvidamos"));
        assertEquals(4, gestor.contarVocales("palindromo"));
        assertNotEquals(1, gestor.contarVocales("hola"));
    }
    
    @Test
    public void testContarVocalesConEspacios() {
        assertEquals(5, gestor.contarVocales("pepe con un pan"));
        assertEquals(9, gestor.contarVocales("bienvenido caballero"));
        assertEquals(4, gestor.contarVocales("pompon blanco"));
        assertNotEquals(5, gestor.contarVocales("El carmin son bichos muertos"));
    }
    
    @Test
    public void testContarVocalesConMayusculas() {
        assertEquals(3, gestor.contarVocales("hAblAmE"));
        assertEquals(4, gestor.contarVocales("OlvidAmoS"));
        assertEquals(4, gestor.contarVocales("palIndromO"));
        assertNotEquals(1, gestor.contarVocales("hOLa"));
    }
    
    @Test
    public void testContarVocalesMezcla() {
        assertEquals(2, gestor.contarVocales("bb/*a a/*"));
        assertEquals(1, gestor.contarVocales("!<!ds a4342"));
        assertEquals(1, gestor.contarVocales("23# @|daw13dw3·"));
        assertNotEquals(5, gestor.contarVocales("2817rgy82bf 518--*-650"));
    }

**Comment by marcosgilson** [comment]
Solucionado.
