### ISSUE TITLE
¿Las tíldes se deben incluir en un palindromo?

### ISSUE THREAD

**Issue by gonzaga24** [Jaim8RR/GestorPalabras#7]
![imagen](https://github.com/Jaim8RR/GestorPalabras/assets/153544688/957008b7-dffb-4610-bfa3-82dbb5a61863)

**Comment by Jaim8RR** [comment]
Las tildes sí deberían de serlo, al menos según la RAE:
![image](https://github.com/Jaim8RR/GestorPalabras/assets/153544634/28783ada-0a55-48f4-b260-4fc6aed40633)

**Comment by gonzaga24** [comment]
Se han añadido las tildes al metodo esPalindromo
